server:
  port: 80
  tomcat:
    max-threads: 1000
    min-spare-threads: 500

# 测试@Value属性的 配置方式
myname: yang
myconfig:
  age: 22
  address:
    city: 北京
    phone: 18765829080

# 整合 jsp 的时候的配置
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: test
  datasource:
    bloom:
#      jdbcUrl: jdbc:mysql://localhost:3306/bloom_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
      jdbcUrl: jdbc:mysql://localhost:3306/mysql_youhua?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: bloom
  redis:
    host: 192.168.120.157
    port: 6379
###### adminUI-client 监控中心的配置项(作为被监控端的配置), 这里先注释掉####
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

###### springboot 整合mybatis + pageHelper 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

### 配置日志级别
logging:
  level:
    org:
      apache:
        ibatis: debug
    com:
      deepblue:
        bloom:
          mapper: debug
        product:
          mapper: debug
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
  page-size-zero: true



#singleServerConfig:
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  reconnectionTimeout: 3000
#  failedAttempts: 3
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  address: "redis://127.0.0.1:6379"
#  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 50
#  connectionMinimumIdleSize: 32
#  connectionPoolSize: 64
#  database: 0
#  dnsMonitoring: false
#  dnsMonitoringInterval: 5000
#threads: 0
#nettyThreads: 0
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
#"transportMode":"NIO"



###### springboot 监控中心的配置, 这里先注释掉
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"


# mybatis plus 全局配置模式(针对于mybatis-plus所连接的数据库起作用,本人测试没有起作用,用的是默认的,写了一个类进行处理)
#mybatis-plus:
#  global-config:
#    db-config:
#      #mybatis-plus所连接的数据库的主键策略
#      #id-type: AUTO
#      #mybatis-plus所连接的数据库表中前缀的配置
#      table-prefix: table_